"""
make_version_info.py  -  Generate a PyInstaller Windows version resource for ReClip.exe.

SignPath Foundation requires signed binaries to carry stable product metadata
(ProductName and ProductVersion) that it can enforce with file metadata
restrictions. This script writes the VSVersionInfo file that PyInstaller
embeds through --version-file.

Run:  python make_version_info.py <version> [output-path]
      <version> is a git tag such as v1.6.5 or a bare 1.6.5. Anything that
      does not parse as up to four dotted integers becomes 0.0.0.0.
"""

import re
import sys
from datetime import date

PRODUCT_NAME = "ReClip"
COMPANY_NAME = "ReClip"
DESCRIPTION = "ReClip - local video and audio downloader"
ORIGINAL_FILENAME = "ReClip.exe"
DEFAULT_OUTPUT = "version_info.txt"

TEMPLATE = """# UTF-8
# Generated by make_version_info.py - do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={tuple_version},
    prodvers={tuple_version},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [StringStruct('CompanyName', '{company}'),
         StringStruct('FileDescription', '{description}'),
         StringStruct('FileVersion', '{dotted_version}'),
         StringStruct('InternalName', '{product}'),
         StringStruct('LegalCopyright', '{copyright}'),
         StringStruct('OriginalFilename', '{original_filename}'),
         StringStruct('ProductName', '{product}'),
         StringStruct('ProductVersion', '{dotted_version}')])
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])])
  ]
)
"""


def parse_version(raw: str) -> tuple[int, int, int, int]:
    """Turn 'v1.6.5', '1.6.5', or '1.6.5.2' into a four-part integer tuple."""
    text = raw.strip()
    if text.lower().startswith("v"):
        text = text[1:]
    match = re.fullmatch(r"(\d+)(?:\.(\d+))?(?:\.(\d+))?(?:\.(\d+))?", text)
    if not match:
        return (0, 0, 0, 0)
    parts = [int(part) if part is not None else 0 for part in match.groups()]
    # Windows stores each component as an unsigned 16-bit integer.
    return tuple(min(part, 65535) for part in parts)  # type: ignore[return-value]


def render(version: tuple[int, int, int, int]) -> str:
    dotted = ".".join(str(part) for part in version)
    return TEMPLATE.format(
        tuple_version=repr(version),
        dotted_version=dotted,
        company=COMPANY_NAME,
        description=DESCRIPTION,
        product=PRODUCT_NAME,
        original_filename=ORIGINAL_FILENAME,
        copyright=f"Copyright (c) {date.today().year} ReClip contributors. MIT License.",
    )


def main(argv: list[str]) -> int:
    if len(argv) < 2 or argv[1] in {"-h", "--help"}:
        print(__doc__.strip())
        return 2
    version = parse_version(argv[1])
    output = argv[2] if len(argv) > 2 else DEFAULT_OUTPUT
    with open(output, "w", encoding="utf-8") as handle:
        handle.write(render(version))
    print(f"Wrote {output} with version {'.'.join(map(str, version))}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
